services:
  retreat-backend:
    build:
      context: .
    image: kirillshakhov/retreat-backend:1.0
    container_name: retreat-backend
    volumes:
      - "${DOWNLOAD_DIR_PATH:-./downloads}:/app/downloads"
      - "${DATA_DIR_PATH:-./data}:/app/data"
    ports:
      - '8000:8000'
    networks:
      net:
        aliases:
          - retreat-backend
  frontend:
    image: kirillshakhov/retreat-backend:1.0
    pull_policy: always
    container_name: frontend
    networks:
      - net
    ports:
      - '3000:3000'
  mongodb:
    image: public.ecr.aws/docker/library/mongo:8.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: testadmin
      MONGO_INITDB_ROOT_PASSWORD: testadmin
      MONGO_INITDB_DATABASE: retreat
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - net
    ports:
      - '27017:27017'

networks:
  net:
    driver: bridge

volumes:
  mongodb_data:
